### PR TITLE
First analyses

### PR DESCRIPTION
**Pull request by ym-pett**
hm so here's the first draft of code to get descriptives out for sequences and sequences per participant, but there's a problem as it gives me only 9 sequences for ambulating ('4'), but that's incorrect when i look at your plots. possibly the total number of sequences, 488 is also incorrect. will investigate but could do with a second pair of eyes, cheers!

### CODE REVIEW

**Comment by mwibrow** [comment]
The `count_datapoints` function takes an argument, but then ignores it and uses the (global) variable `mini`:
```
def count_datapoints(part):
    # ...lines omitted
    for _, v in mini.groupby((part['activity'].shift() != part['activity']).cumsum()):
```

could this be the reason for the confusing figures?

**Comment by ym-pett** [comment]
> The `count_datapoints` function takes an dataframe argument, but then ignores it and uses the (global) variable `mini`:
> 
> ```
> def count_datapoints(part):
>     # ...lines omitted
>     for _, v in mini.groupby((part['activity'].shift() != part['activity']).cumsum()):
> ```
> 
> could this be the reason for the confusing figures?
> 
> Other than that, this is all useful stuff.

:facepalm:  ffs michèle it had to be something like that, it's not like i haven't done that one before. will fix then we can discuss results. cheers!

**Comment by mwibrow** [comment]
Not sure about this, but looking at the plot for **Get an idea of the distribution of numbers of sequences in all particpants**, I wonder whether a bar chart could also work here?:

```
part_s['activity_type']['count'].astype(int).value_counts().sort_index().plot.bar()
```

Produces this:

Screenshot 2020-09-18 at 14 20 59

**Comment by ym-pett** [comment]
> Not sure about this, but looking at the plot for **Get an idea of the distribution of numbers of sequences in all particpants**, I wonder whether a bar chart could also work here?:
> 
> ```
> part_s['activity_type']['count'].astype(int).value_counts().sort_index().plot.bar()
> ```
> 
> Produces this:
> 
> Screenshot 2020-09-18 at 14 20 59
> 
> Probably doesn't matter though

I think that's a much nicer way to represent it - want to make the change or should I?

**Comment by mwibrow** [comment]
probably best if you do it, so we don't tread on each others toes in the same branch

**Comment by ym-pett** [comment]
> probably best if you do it, so we don't tread on each others toes in the same branch

done :)

**Pull request merged**
